version: '3.5'

services:
  db_test:
    container_name: db_test
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres:14.3-alpine